### Step 1 : Import required Libraries

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

### Step 2 : Load the Dataset

In [ ]:
df = pd.read_csv("/content/Dataset .csv")

In [ ]:
df

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,Naml۱ Gurme,208,��stanbul,"Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...",Karak�_y,"Karak�_y, ��stanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz A��ac۱,208,��stanbul,"Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...",Ko��uyolu,"Ko��uyolu, ��stanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,A���k Kahve,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,��stanbul,"Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...",Moda,"Moda, ��stanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

### Step 3 : Data Preprocessing

1. Feature Selection

In [ ]:
features = [
    "Average Cost for two",
    "Price range",
    "Has Online delivery",
    "Has Table booking",
    "Country Code",
    "Cuisines"
]

In [ ]:
df = df[features]

In [ ]:
df

,Average Cost for two,Price range,Has Online delivery,Has Table booking,Country Code,Cuisines
0,1100,3,No,Yes,162,"French, Japanese, Desserts"
1,1200,3,No,Yes,162,Japanese
2,4000,4,No,Yes,162,"Seafood, Asian, Filipino, Indian"
3,1500,4,No,No,162,"Japanese, Sushi"
4,1500,4,No,Yes,162,"Japanese, Korean"
...,...,...,...,...,...,...
9546,80,3,No,No,208,Turkish
9547,105,3,No,No,208,"World Cuisine, Patisserie, Cafe"
9548,170,4,No,No,208,"Italian, World Cuisine"
9549,120,4,No,No,208,Restaurant Cafe
9550,55,2,No,No,208,Cafe

2. Handling the Missing Values

In [ ]:
df.isnull().sum()

Average Cost for two    0
Price range             0
Has Online delivery     0
Has Table booking       0
Country Code            0
Cuisines                9
dtype: int64

In [ ]:
df["Cuisines"] = df["Cuisines"].fillna("Unknown")

/tmp/ipython-input-2974592496.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Cuisines"] = df["Cuisines"].fillna("Unknown")

In [ ]:
df.isnull().sum()

Average Cost for two    0
Price range             0
Has Online delivery     0
Has Table booking       0
Country Code            0
Cuisines                0
dtype: int64

### Step 4 : Categorical Value Encoding

In [ ]:
df["Has Online delivery"] = df["Has Online delivery"].map({"Yes": 1, "No": 0})

/tmp/ipython-input-1094786003.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Has Online delivery"] = df["Has Online delivery"].map({"Yes": 1, "No": 0})

In [ ]:
df["Has Table booking"] = df["Has Table booking"].map({"Yes": 1, "No": 0})

/tmp/ipython-input-3520334388.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Has Table booking"] = df["Has Table booking"].map({"Yes": 1, "No": 0})

In [ ]:
df

,Average Cost for two,Price range,Has Online delivery,Has Table booking,Country Code,Cuisines
0,1100,3,0,1,162,"French, Japanese, Desserts"
1,1200,3,0,1,162,Japanese
2,4000,4,0,1,162,"Seafood, Asian, Filipino, Indian"
3,1500,4,0,0,162,"Japanese, Sushi"
4,1500,4,0,1,162,"Japanese, Korean"
...,...,...,...,...,...,...
9546,80,3,0,0,208,Turkish
9547,105,3,0,0,208,"World Cuisine, Patisserie, Cafe"
9548,170,4,0,0,208,"Italian, World Cuisine"
9549,120,4,0,0,208,Restaurant Cafe
9550,55,2,0,0,208,Cafe

### Step 5 : Define Features and Target Variable

In [ ]:
X = df.drop(columns="Cuisines")

# Extract primary cuisine for each Restaurant
df["Primary Cuisine"] = df["Cuisines"].apply(lambda x: x.split(",")[0])

y = df["Primary Cuisine"]

/tmp/ipython-input-717751206.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Primary Cuisine"] = df["Cuisines"].apply(lambda x: x.split(",")[0])

In [ ]:
y

0                French
1              Japanese
2               Seafood
3              Japanese
4              Japanese
             ...
9546            Turkish
9547      World Cuisine
9548            Italian
9549    Restaurant Cafe
9550               Cafe
Name: Primary Cuisine, Length: 9551, dtype: object

In [ ]:
# Converting the target variable into numerical values

le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
X

,Average Cost for two,Price range,Has Online delivery,Has Table booking,Country Code
0,1100,3,0,1,162
1,1200,3,0,1,162
2,4000,4,0,1,162
3,1500,4,0,0,162
4,1500,4,0,1,162
...,...,...,...,...,...
9546,80,3,0,0,208
9547,105,3,0,0,208
9548,170,4,0,0,208
9549,120,4,0,0,208
9550,55,2,0,0,208

In [ ]:
y

array([39, 55, 97, ..., 54, 93, 23])

### Step 6 : Split the Dataset into Training and Testing Datasets

1. Filter Rare Cuisine Classes

In [ ]:
# Keep cuisines with sufficient samples
cuisine_counts = pd.Series(y).value_counts()
valid_classes = cuisine_counts[cuisine_counts >= 5].index

mask = pd.Series(y).isin(valid_classes)
X = X[mask]
y = y[mask]

2. Split Data

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
X_train.shape

(7562, 5)

In [ ]:
X_test.shape

(1891, 5)

In [ ]:
X.shape

(9453, 5)

### Step 7 : Train Classification Model

In [ ]:
Model = RandomForestClassifier(n_estimators=100, random_state=42)

In [ ]:
Model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

### Step 8: Evaluate the Model

In [ ]:
y_pred = Model.predict(X_test)

In [ ]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

Accuracy: 0.3358011634056055

Classification Report:

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           2       0.24      0.36      0.28        56
           4       0.00      0.00      0.00         1
           6       0.00      0.00      0.00        15
          10       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         4
          12       0.14      0.02      0.03       124
          13       0.00      0.00      0.00         2
          14       0.00      0.00      0.00         4
          15       0.00      0.00      0.00        16
          17       0.00      0.00      0.00        22
          18       0.20      0.25      0.22         4
          19       0.00      0.00      0.00         5
          20       0.11      0.50      0.18         2
          21       0.00      0.00      0.00        23
          23       0.35      0.24      0.29       124
          27       0.20      0.02      0.04       171
          28       0.00      0.00      0.00         2
          30       0.10      0.09      0.09        47
          33       0.00      0.00      0.00        30
          35       0.11      0.08      0.10        12
          36       0.09      0.03      0.04       135
          37       0.00      0.00      0.00         1
          38       0.15      0.12      0.14        16
          39       0.00      0.00      0.00         3
          41       0.00      0.00      0.00         2
          43       0.00      0.00      0.00         1
          45       0.00      0.00      0.00         1
          46       0.00      0.00      0.00         1
          47       0.00      0.00      0.00        11
          48       0.00      0.00      0.00         2
          49       0.00      0.00      0.00        36
          50       0.25      0.20      0.22        10
          52       0.00      0.00      0.00         3
          54       0.25      0.15      0.19        47
          55       0.00      0.00      0.00        14
          56       0.00      0.00      0.00         2
          57       0.00      0.00      0.00         3
          58       0.67      1.00      0.80         2
          59       0.00      0.00      0.00         3
          61       0.00      0.00      0.00         2
          62       0.00      0.00      0.00         1
          63       0.00      0.00      0.00         5
          64       0.00      0.00      0.00         1
          65       0.00      0.00      0.00         1
          66       0.00      0.00      0.00         1
          68       0.00      0.00      0.00         6
          69       0.00      0.00      0.00        12
          71       0.29      0.41      0.34        49
          73       0.00      0.00      0.00         3
          74       0.00      0.00      0.00        43
          75       0.00      0.00      0.00         1
          78       0.00      0.00      0.00         1
          79       0.37      0.86      0.52       599
          81       0.00      0.00      0.00         2
          82       0.00      0.00      0.00         1
          87       0.33      0.33      0.33        46
          88       0.00      0.00      0.00         1
          90       0.00      0.00      0.00         1
          92       0.00      0.00      0.00        22
          95       0.00      0.00      0.00         1
          97       0.25      0.10      0.14        10
         100       0.00      0.00      0.00        53
         101       0.00      0.00      0.00         1
         104       0.00      0.00      0.00         3
         105       0.33      0.06      0.11        47
         107       0.00      0.00      0.00         3
         110       0.00      0.00      0.00         3
         112       0.00      0.00      0.00         6
         113       0.00      0.00      0.00         4
         114       0.00      0.00      0.00         1
         116       0.00      0.00      0.00         2

    accuracy                           0.34      1891
   macro avg       0.06      0.07      0.06      1891
weighted avg       0.22      0.34      0.23      1891

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[ 0  0  0 ...  0  0  0]
 [ 0 20  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  1  0 ...  0  0  0]]